import { defineConfig } from 'cspell';

export default defineConfig({
  dictionaries: ['npm', 'typescript', 'node', 'html', 'css'],
  words: [
    'aceito',
    'estados',
    'greetng',
    'início',
    'inglês',
    'itens',
    'laranja',
    'maçã',
    'messageformat',
    'minutos',
    'nvmrc',
    'pagar',
    'plik',
    'pliki',
    'pliku',
    'plików',
    'português',
    'renderable',
    'sehv',
    'shiki',
    'subtag',
    'subtags',
    'termos',
    'typesafe',
    'unidos',
    'unparseable',
    'vindo',
    'você',
  ],
  ignorePaths: ['pnpm-lock.yaml', 'CHANGELOG.md'],
  useGitignore: true,
});
