packages:
  - packages/core
  - packages/react
  - examples

allowBuilds:
  esbuild: false

engineStrict: true

catalog:
  '@changesets/cli': 3.0.0
  '@tailwindcss/vite': 4.3.3
  '@types/node': 26.2.0
  '@types/react': ^19.0.0
  '@vitejs/plugin-react': 6.0.5
  '@vitest/browser-playwright': 4.1.10
  '@vitest/coverage-v8': 4.1.10
  autoprefixer: 10.5.4
  cspell: 10.0.1
  eslint: 10.8.1
  playwright: 1.62.1
  postcss: 8.5.26
  prettier: 3.9.6
  react: ^19.0.0
  react-dom: ^19.0.0
  shiki: 4.4.3
  tailwindcss: 4.3.3
  tsdown: 0.22.14
  typescript: 7.0.2
  vite: 8.2.1
  vitest: 4.1.10
  vitest-browser-react: 2.2.0
  yaml: 2.9.0
